// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLoRuargnjQ4lxGZJQ5kxu4O1lZ4SDsak',
    appId: '1:695207975863:web:a37892c9be5226c117e632',
    messagingSenderId: '695207975863',
    projectId: 'inventory-app-kevin',
    authDomain: 'inventory-app-kevin.firebaseapp.com',
    storageBucket: 'inventory-app-kevin.firebasestorage.app',
    measurementId: 'G-JG0PQ8KHNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC04DdATMlJlDUYsg3w-DnKU97k1ZVpg20',
    appId: '1:695207975863:android:a65e1a3c14ce3b1e17e632',
    messagingSenderId: '695207975863',
    projectId: 'inventory-app-kevin',
    storageBucket: 'inventory-app-kevin.firebasestorage.app',
  );
}
